name: CD
on:
  push:
    branches:
      - main

jobs:
  deployed:
    runs-on: ubuntu-latest

    steps:
      - name: install checkout
        uses: actions/checkout@v7

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'npm'

      - name: install dependencies
        run: npm install

      - name: build app
        run: npm build

      - name: Upload app to https
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          source: "out"
          target: "var/www/httpdocs/"
